<a href="https://colab.research.google.com/github/yfhkucing/Tensorflow_playground/blob/master/TFPlayground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [2]:
#for constant variable, for changeable variable use tf.variable()
#scalar
scalar = tf.constant(7)
#vector
vector = tf.constant([7,2])
#matrix
matrix = tf.constant([[1,2,3],
                     [4,5,6]])
#tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6],
                       [2,3,3],
                       [4,5,7]],
                      [[1,2,3],
                       [4,5,6],
                       [2,3,3],
                       [4,5,7]]])
print(scalar.ndim)
print(vector.ndim)
print(matrix.ndim)
print(tensor.ndim)
tensor

0
1
2
3


<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [2, 3, 3],
        [4, 5, 7]],

       [[1, 2, 3],
        [4, 5, 6],
        [2, 3, 3],
        [4, 5, 7]]], dtype=int32)>

In [3]:
#random tensor
random_tensor = tf.random.Generator.from_seed(42)
random_tensor = random_tensor.normal(shape= (3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [4]:
random_tensor2 = tf.random.Generator.from_seed(42)
random_tensor2 = random_tensor2.normal(shape= (3,2))
random_tensor2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [5]:
#shuffle a tensor
tensor3 = tf.constant([[10,7],
                      [3,4],
                      [7,9]])
tf.random.shuffle(tensor3)          

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7,  9],
       [ 3,  4]], dtype=int32)>

In [6]:
#indexing tensor
tensor3.ndim
tensor3[:3,:2]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 7,  9]], dtype=int32)>

In [7]:
rank_4_tensor = tf.zeros([4,3,5,6])
#rank_4_tensor.ndim
print(rank_4_tensor[:2,:2,:1,:2])

tf.Tensor(
[[[[0. 0.]]

  [[0. 0.]]]


 [[[0. 0.]]

  [[0. 0.]]]], shape=(2, 2, 1, 2), dtype=float32)


In [8]:
rank_4_tensor[:3,:3,:3,-1]

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [9]:
# tensor basic operation
#addition
tensor1 = tf.constant([[10,7],
                      [3,4]])
tensor1 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [10]:
#multiply
tensor1 * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [11]:
#using built in tensorflow operation
#tf.math.multiply(a,b)
tf.multiply(tensor1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [12]:
# matrix multiplication (dot product)
#tf.linalg.matmul
tf.matmul(tensor1,tensor1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [13]:
tensor2 = tf.constant([[1,2,5],
                       [7,2,1],
                       [3,3,3]])
tensor3 = tf.constant([[3,5],
                       [6,7],
                       [1,8]])
tf.matmul(tensor2,tensor3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [14]:
tensor2 = tf.constant([[1,2],
                       [7,2],
                       [3,3]])
tensor3 = tf.constant([[3,5],
                       [6,7],
                       [1,8]])
transpose3 = tf.transpose(tensor3)
print(transpose3)
tf.matmul(tensor2,tf.transpose(tensor3))

tf.Tensor(
[[3 6 1]
 [5 7 8]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 20, 17],
       [31, 56, 23],
       [24, 39, 27]], dtype=int32)>

In [21]:
#aggregating tensor (condensing tensor)
D = tf.constant([-7,-10])
# absolute value
print(tf.abs(D))
#min value
print(tf.reduce_min(D))
#max value
print(tf.reduce_max(D))
#mean value
print(tf.reduce_mean(D))

tf.Tensor([ 7 10], shape=(2,), dtype=int32)
tf.Tensor(-10, shape=(), dtype=int32)
tf.Tensor(-7, shape=(), dtype=int32)
tf.Tensor(-8, shape=(), dtype=int32)


In [26]:
import numpy as np
#troubleshooting tensor
D = tf.constant([[np.random.randint(low=0, high=100, size=50)],[np.random.randint(low=0, high=100, size=50)]])

<tf.Tensor: shape=(2, 1, 50), dtype=int32, numpy=
array([[[46, 67, 99, 79,  3, 76, 83, 11, 58, 92,  8, 96, 59, 34,  0, 47,
         10, 83, 48, 16, 59, 93, 51, 50, 64, 53, 25, 92, 96, 81, 21, 99,
         89,  5, 76, 29, 80,  4, 29, 95, 65, 18, 76, 98, 56, 67, 74, 93,
          1, 29]],

       [[95,  0, 65, 66, 66, 67, 91, 27, 82, 18,  3, 56, 98, 44, 19, 78,
         96, 18, 77, 80, 72, 78, 30,  7, 16, 27,  8,  0, 88, 83, 61, 43,
         99, 80, 79, 30, 14, 52, 81, 71, 16, 74, 94, 94, 65, 15,  8, 76,
         56, 24]]], dtype=int32)>

In [27]:
import tensorflow_probability as tfp
#variance of tensor
tfp.stats.variance(D)

<tf.Tensor: shape=(1, 50), dtype=int32, numpy=
array([[ 600, 1122,  289,   42,  992,   20,   16,   64,  144, 1369,    6,
         400,  380,   25,   90,  240, 1849, 1056,  210, 1024,   42,   56,
         110,  462,  576,  169,   72, 2116,   16,    1,  400,  784,   25,
        1406,    2,    0, 1089,  576,  676,  144,  600,  784,   81,    4,
          20,  676, 1089,   72,  756,    6]], dtype=int32)>

In [28]:
tf.math.reduce_std(tf.cast(D,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=31.713245>

In [36]:
#positional max and min of tensor
#tf.argmin(D)
tf.argmax(D)

<tf.Tensor: shape=(1, 50), dtype=int64, numpy=
array([[1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
        1, 0, 0, 0, 1, 0]])>